# Generated by Django 4.0.4 on 2023-10-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customer_id_alter_order_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Gaming', 'Gaming'), ('Macbook', 'Macbook'), ('Desktop', 'Desktop'), ('Chromebook', 'Chromebook')], max_length=200, null=True),
        ),
    ]
