# Generated by Django 4.0.4 on 2023-10-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_tags_product_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Brand',
        ),
    ]
